### ISSUE TITLE
プロジェクト検索の改良

### ISSUE THREAD

**Issue by nishio-dens** [library-miner/library-miner-web-api#3]
Search::Project の match_to_all_dependency_library はパット見てやばい。
多分件数が増えたらレスポンスが帰ってこなくなる。

理想は検索エンジン使うことだが、最初のフェーズではDB検索でなんとかしたい。
ので、このクエリは改良したい。

**Comment by quick-xp** [comment]
JOIN をつなげて検索するように改良する(そのため検索項目の制限を課す）
